name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  shared:
    uses: vision-web3/ci-workflows/.github/workflows/python-ci.yml@v1

  docker-build:
    runs-on: ubuntu-latest
    needs: [shared]
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      - name: Build and load
        run: |
          docker buildx build \
            --cache-from=type=gha \
            --platform=linux/amd64 \
            --build-arg environment=testnet \
            --builder ${{ steps.buildx.outputs.name }} \
            --load \
            --tag ghcr.io/vision-web3/client-cli:latest \
            .

      - name: Test image
        run: |
          docker run --rm ghcr.io/vision-web3/client-cli:latest --help

  build-and-run:
    runs-on: ubuntu-latest
    needs: [shared]
    steps:
      - uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
     
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        uses: vision-web3/ci-workflows/.github/actions/install-python-deps@v1

      - name: Run program
        run: |
          source .venv/bin/activate
          ./vision-client.sh --help

  build:
    uses: ./.github/workflows/build.yml
