name: Publish dev release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and attach .deb and .whl package
    if: github.repository == 'vision-web3/client-cli'
    uses: ./.github/workflows/build.yaml
    secrets: 'inherit'

  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    if: github.repository == 'vision-web3/client-cli'
    needs: build
    secrets: 'inherit'
    with:
      tag: development
      environment: main
